openapi: 3.0.3
info:
  title: API LivroAdmin
  description: Projeto de uma API REST desenvolvida com Expressjs
  version: 0.1.0
servers:
  - url: http://localhost:3000/
    description: Ambiente de Desenvolvimento
tags:
  - name: usuario
  - name: login
  - name: categoria de livro
  - name: autor de livro
  - name: tamanho de livro
  - name: livro
  - name: estoque de livro
paths:
  /api/v1/usuario:
    post:
      summary: Criar usuário
      description: Cria um novo usuário.
      tags: 
         - usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/usuario'
      responses:
        422:
          $ref: '#/components/responses/erro422'
        500:
          $ref: '#/components/responses/erro500'
        201:
          description: Usuário cadastrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/usuario'
    get:
      summary: Listar usuários
      security:
        - bearerAuth: []
      description: Lista de todos os usuários cadastrados.
      tags: 
         - usuario
      responses:
        401:
          $ref: '#/components/responses/erro401'
        500:
          $ref: '#/components/responses/erro500'
        200:
          description: Listagem de todos os usuários cadastrados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/usuario'
  /api/v1/usuario/{id}:
    get:
      summary: Lista usuário
      security:
        - bearerAuth: []
      description: Lista um usuários.
      tags: 
         - usuario
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        400:
          $ref: '#/components/responses/erro400'
        401:
          $ref: '#/components/responses/erro401'
        404:
          $ref: '#/components/responses/erro404'
        500:
          $ref: '#/components/responses/erro500'
        200:
          description: Token de autentificação
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/usuario'
    put:
      summary: Edita usuário
      security:
        - bearerAuth: []
      description: Edita um usuários.
      tags: 
         - usuario
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/usuario'
      responses:
        400:
          $ref: '#/components/responses/erro400'
        401:
          $ref: '#/components/responses/erro401'
        404:
          $ref: '#/components/responses/erro404'
        500:
          $ref: '#/components/responses/erro500'
        200:
          description: só pra passar
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/usuario'
    delete:
      summary: Deleta usuário
      security:
        - bearerAuth: []
      description: Deleta um usuários.
      tags: 
         - usuario
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        400:
          $ref: '#/components/responses/erro400'
        401:
          $ref: '#/components/responses/erro401'
        404:
          $ref: '#/components/responses/erro404'
        500:
          $ref: '#/components/responses/erro500'
        204:
          description: Recurso deletado com sucesso

  /api/v1/usuario/login:
    post:  
      summary: Realiza login
      description: Faz autentificação do usuários e gera um token de validação.
      tags: 
         - login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/login'
      responses:
        401:
          $ref: '#/components/responses/erro401login'
        500:
          $ref: '#/components/responses/erro500'
        200:
          description: só pra passar
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/token'
  /api/v1/usuario/renova:
    post:
      summary: Renova token
      description: Renova a validade de um token de validação.
      tags: 
         - login
      responses:
        401:
          $ref: '#/components/responses/erro401'
        500:
          $ref: '#/components/responses/erro500'
        200:
          description: só pra passar
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/token'

  /api/v1/livro/categoria:
    post:
      summary: Cria categoria
      security:
        - bearerAuth: []
      description: Cria um nova categoria.
      tags: 
         - categoria de livro
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/categoria'
      responses:
        401:
          $ref: '#/components/responses/erro401'
        422:
          $ref: '#/components/responses/erro422'
        500:
          $ref: '#/components/responses/erro500'
        201:
          description: só pra passar
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/categoria'
    get:
      summary: Lista categorias
      description: Lista todas as categorias.
      tags: 
         - categoria de livro
      responses:
        500:
          $ref: '#/components/responses/erro500'
        200:
          description: só pra passar
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/categoria'
  /api/v1/livro/categoria/{id}:
    put:
      summary: Edita categoria
      security:
        - bearerAuth: []
      description: Edita uma categoria em todas as tabelas.
      tags: 
         - categoria de livro
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/categoria'
      responses:
        400:
          $ref: '#/components/responses/erro400'
        401:
          $ref: '#/components/responses/erro401'
        404:
          $ref: '#/components/responses/erro404'
        500:
          $ref: '#/components/responses/erro500'
        200:
          description: só pra passar
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/categoria'
    get:
      summary: Lista categoria
      description: Lista uma categoria.
      tags: 
         - categoria de livro
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        400:
          $ref: '#/components/responses/erro400'
        404:
          $ref: '#/components/responses/erro404'
        500:
          $ref: '#/components/responses/erro500'
        200:
          description: só pra passar
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/categoria'
    delete:
      summary: Deleta categoria
      security:
        - bearerAuth: []
      description: Deleta uma categoria em todas as tabelas.
      tags: 
         - categoria de livro
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        400:
          $ref: '#/components/responses/erro400'
        401:
          $ref: '#/components/responses/erro401'
        404:
          $ref: '#/components/responses/erro404'
        500:
          $ref: '#/components/responses/erro500'
        204:
          description: Recurso deletado com sucesso

  /api/v1/livro/autor:
    post:
      summary: Cria autor
      security:
        - bearerAuth: []
      description: Cria um novo autor.
      tags: 
         - autor de livro
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/autor'
      responses:
        401:
          $ref: '#/components/responses/erro401'
        422:
          $ref: '#/components/responses/erro422'
        500:
          $ref: '#/components/responses/erro500'
        201:
          description: só pra passar
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/autor'
    get:
      summary: Lista autores
      description: Lista todos os autores.
      tags: 
         - autor de livro
      responses:
        500:
          $ref: '#/components/responses/erro500'
        200:
          description: só pra passar
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/autor'
  /api/v1/livro/autor/{id}:
    put:
      summary: Edita autor
      security:
        - bearerAuth: []
      description: Edita um autor em todas as tabelas.
      tags: 
         - autor de livro
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/autor'
      responses:
        400:
          $ref: '#/components/responses/erro400'
        401:
          $ref: '#/components/responses/erro401'
        404:
          $ref: '#/components/responses/erro404'
        500:
          $ref: '#/components/responses/erro500'
        200:
          description: só pra passar
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/autor'
    get:
      summary: Lista autor
      description: Lista um autor.
      tags: 
         - autor de livro
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        400:
          $ref: '#/components/responses/erro400'
        404:
          $ref: '#/components/responses/erro404'
        500:
          $ref: '#/components/responses/erro500'
        200:
          description: só pra passar
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/autor'
    delete:
      summary: Deleta autor
      security:
        - bearerAuth: []
      description: Deleta um autor em todas as tabelas.
      tags: 
         - autor de livro
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        400:
          $ref: '#/components/responses/erro400'
        404:
          $ref: '#/components/responses/erro404'
        500:
          $ref: '#/components/responses/erro500'
        204:
          description: Recurso deletado com sucesso

  /api/v1/livro/tamanho:
    post:
      summary: Cria tamanho
      security:
        - bearerAuth: []
      description: Cria um novo tamanho.
      tags: 
         - tamanho de livro
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tamanho'
      responses:
        401:
          $ref: '#/components/responses/erro401'
        422:
          $ref: '#/components/responses/erro422'
        500:
          $ref: '#/components/responses/erro500'
        201:
          description: só pra passar
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tamanho'
    get:
      summary: Lista tamanhos
      description: Lista todos os tamanhos.
      tags: 
         - tamanho de livro
      responses:
        500:
          $ref: '#/components/responses/erro500'
        200:
          description: só pra passar
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/tamanho'
  /api/v1/livro/tamanho/{id}:
    put:
      summary: Edita tamanho
      security:
        - bearerAuth: []
      description: Edita um tamanho em todas as tabelas.
      tags: 
         - tamanho de livro
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tamanho'
      responses:
        400:
          $ref: '#/components/responses/erro400'
        401:
          $ref: '#/components/responses/erro401'
        404:
          $ref: '#/components/responses/erro404'
        500:
          $ref: '#/components/responses/erro500'
        200:
          description: só pra passar
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tamanho'
    get:
      description: Lista um tamanho.
      summary: Lista tamanho
      tags: 
         - tamanho de livro
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        400:
          $ref: '#/components/responses/erro400'
        404:
          $ref: '#/components/responses/erro404'
        500:
          $ref: '#/components/responses/erro500'
        200:
          description: só pra passar
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tamanho'
    delete:
      summary: Deleta tamanho
      security:
        - bearerAuth: []
      description: Deleta um tamanho em todas as tabelas.
      tags: 
         - tamanho de livro
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        400:
          $ref: '#/components/responses/erro400'
        401:
          $ref: '#/components/responses/erro401'
        404:
          $ref: '#/components/responses/erro404'
        500:
          $ref: '#/components/responses/erro500'
        204:
          description: Recurso deletado com sucesso

  /api/v1/livro:
    post:
      summary: Cria livro
      security:
        - bearerAuth: []
      description: Cria um novo livro.
      tags: 
         - livro
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/livro'
      responses:
        400:
          $ref: '#/components/responses/erro400'
        401:
          $ref: '#/components/responses/erro401'
        404:
          $ref: '#/components/responses/erro404item'
        422:
          $ref: '#/components/responses/erro422'
        201:
          description: só pra passar
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/livroPopulado'
    get:
      summary: Lista livros
      description: Lista todos os livros.
      tags: 
         - livro
      responses:
        500:
          $ref: '#/components/responses/erro500'
        200:
          description: só pra passar
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/livroPopulado'
  /api/v1/livro/{id}:
    put:
      summary: Edita livro
      security:
        - bearerAuth: []
      description: Edita um livro em todas as tabelas.
      tags: 
         - livro
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/livro'
      responses:
        400:
          $ref: '#/components/responses/erro400'
        401:
          $ref: '#/components/responses/erro401'
        404:
          $ref: '#/components/responses/erro404'
        422:
          $ref: '#/components/responses/erro422'
        500:
          $ref: '#/components/responses/erro500'
        200:
          description: só pra passar
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/livroPopulado'
    get:
      summary: Lista livro
      description: Lista um livro.
      tags: 
         - livro
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        400:
          $ref: '#/components/responses/erro400'
        404:
          $ref: '#/components/responses/erro404'
        500:
          $ref: '#/components/responses/erro500'
        200:
          description: só pra passar
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/livroPopulado'
    delete:
      summary: Deleta livro
      security:
        - bearerAuth: []
      description: Deleta um livro em todas as tabelas.
      tags: 
         - livro
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        400:
          $ref: '#/components/responses/erro400'
        401:
          $ref: '#/components/responses/erro401'
        404:
          $ref: '#/components/responses/erro404'
        500:
          $ref: '#/components/responses/erro500'
        204:
          description: Recurso deletado com sucesso

  /api/v1/livro/estoque:
    post:
      summary: Cria estoque
      security:
        - bearerAuth: []
      description: Cria um novo estoque.
      tags: 
         - estoque de livro
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/estoque'
      responses:
        401:
          $ref: '#/components/responses/erro401'
        404:
          $ref: '#/components/responses/erro404item'
        422:
          $ref: '#/components/responses/erro422'
        500:
          $ref: '#/components/responses/erro500'
        201:
          description: só pra passar
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/estoquePopulado'
    get:
      summary: Lista estoques
      description: Lista todos os estoques.
      tags: 
         - estoque de livro
      responses:
        500:
          $ref: '#/components/responses/erro500'
        200:
          description: só pra passar
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/estoquePopulado'
  /api/v1/livro/estoque/{id}:
    put:
      summary: Edita estoque
      security:
        - bearerAuth: []
      description: Edita um estoque em todas as tabelas.
      tags: 
         - estoque de livro
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/estoque'
      responses:
        400:
          $ref: '#/components/responses/erro400'
        401:
          $ref: '#/components/responses/erro401'
        404:
          $ref: '#/components/responses/erro404'
        422:
          $ref: '#/components/responses/erro422'
        500:
          $ref: '#/components/responses/erro500'
        200:
          description: só pra passar
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/estoquePopulado'
    get:
      summary: Lista estoque
      description: Lista um estoque.
      tags: 
         - estoque de livro
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        400:
          $ref: '#/components/responses/erro400'
        404:
          $ref: '#/components/responses/erro404'
        500:
          $ref: '#/components/responses/erro500'
        200:
          description: só pra passar
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/estoquePopulado'
    delete:
      summary: Deleta estoque
      security:
        - bearerAuth: []
      description: Deleta um estoque em todas as tabelas.
      tags: 
         - estoque de livro
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        400:
          $ref: '#/components/responses/erro400'
        401:
          $ref: '#/components/responses/erro401'
        404:
          $ref: '#/components/responses/erro404'
        500:
          $ref: '#/components/responses/erro500'
        204:
          description: Recurso deletado com sucesso

components:
  schemas:
    usuario:
      type: object
      required: [nome, email, senha]
      properties:
        id:
          type: string
          readOnly: true
        nome:
          type: string
          example: jonas
        email:
          type: string
          example: jonas@gmail.com
        senha:
          writeOnly: true
          type: string
          example: 244466666
    login:
      type: object
      required: [email, senha]
      properties:
        email:
          type: string
          example: jonas@gmail.com
        senha:
          type: string
          example: 244466666
    autor:
      type: object
      required: [nome, idade]
      properties:
        id:
          type: string
          readOnly: true
        nome:
          type: string
          example: Axe of Assis
        idade:
          type: number
          example: 42
        nacionalidade:
          type: string
          example: Brasileiro
    categoria:
      type: object
      required: [nome]
      properties:
        id:
          readOnly: true
          type: string
        nome:
          type: string
          example: Literatura
    tamanho:
      type: object
      required: [nome]
      properties:
        id:
          readOnly: true
          type: string
        nome:
          type: string
          example: Livro de bolso
    livro:  
      type: object
      required: [nome, paginas]
      properties:
        id:
          readOnly: true
          type: string
        nome:
          type: string
          example: Memórias do Brás
        paginas:
          type: number
          example: 240
        autor:
          type: string
          example: Axe of Assis
        categoria:
          type: string
          example: Literatura
    livroPopulado:  
      type: object
      properties:
        id:
          readOnly: true
          type: string
        nome:
          type: string
          example: Memórias do Brás
        paginas:
          type: number
          example: 240
        autor:
          $ref: '#/components/schemas/autor'
        categoria:
          $ref: '#/components/schemas/categoria'
    estoque:
      type: object
      required: [livro, quantidade, tamanho, preco]
      properties:
        id:
          readOnly: true
          type: string
        livro:
          type: string
          example: Memórias do Brás
        quantidade:
          type: number
          example: 24
        tamanho:
          type: string
          example: Livro de bolso
        preco:
          type: number
          example: 1000000000
    estoquePopulado:
      type: object
      properties:
        id:
          readOnly: true
          type: string
        livro:
          $ref: '#/components/schemas/livroPopulado'
        quantidade:
          type: number
          example: 24
        tamanho:
          $ref: '#/components/schemas/tamanho'
        preco:
          type: number
          example: 1000000000
    token:
      type: object
      description: Estrutura de resposta contendo o token de autenticação do usuário.
      properties:
        token:
          type: string
          description: Token JWT gerado após login ou renovação, usado para autenticação nas requisições.
    erro:
      type: object
      description: Estrutura padrão para mensagens de erro retornadas pela API.
      properties:
        mensagem:
          type: string
          description: Mensagem descritiva do erro ocorrido.
        codigo:
          type: integer
          description: Código interno ou HTTP relacionado ao erro.
        detalhes:
          type: string
          description: Informações adicionais sobre o erro, se aplicável.
  responses:
    erro400:
      description: Requisição ruim
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/erro'
          example:
            mensagem: 'erro de "Bad Request".'
            codigo: 400
            detalhes: "O ID enviado na url é inválido."
    erro401:
      description: erro de autentificação
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/erro'
          example:
            mensagem: 'erro de ausência de autentificação.'
            codigo: 401
            detalhes: "O usuário não tem a autentificação necessária para esta request, token ausente."
    erro401login:
      description: erro de validação de credenciais
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/erro'
          example:
            mensagem: 'Login ou senha incorretos.'
            codigo: 401
            detalhes: "As credenciais enviadas são inválidas."
    erro404:
      description: Dado não encontrado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/erro'
          example:
            mensagem: 'Dado solicitado ausente ou inexistente.'
            codigo: 404
            detalhes: "O item solicitado pela request é inexistente ou está indisponível."
    erro404item:
      description: Dado do corpo não encontrado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/erro'
          example:
            mensagem: 'Dado solicitado ausente ou inexistente.'
            codigo: 404
            detalhes: "O item indicado no corpo da requisição é inexistente ou está indisponível."
    erro422:
      description: Entidade não processável
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/erro'
          example:
            mensagem: "Dados do corpo inválidos."
            codigo: 422
            detalhes: "O tipo de dado inserido em um dos campos do corpo é inválido."
    erro500:
      description: erro interno de servidor
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/erro'
          example:
            mensagem: "erro interno do servidor."
            codigo: 500
            detalhes: "Ocorreu um erro interno no servidor."
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
